### ISSUE TITLE
ESPHome configurations should use api.encryption.key instead of api.password

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/airgradient-prometheus#38]
Currently the ESPHome configurations use:

```yaml
api:
  password: !secret api_password
```

But according to the [API Component parameter documentation](https://esphome.io/components/api.html#configuration-variables), that value is deprecated in favor of `api.encryption.key`.

So it should be updated to something like:

```yaml
api:
  encryption:
    key: !secret api_encryption_key
```

And then in the `secrets.yaml` file example in the README:

```yaml
# Encryption key for HA API access.
# Generate a random 32-bit key with `openssl rand -base64 32`
api_encryption_key: BASE64_KEY_HERE

# Set password for OTA updates.
ota_password: otapassword
```
